// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        return macos;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArPrhRDvgLU2qjl1VCmBhed0_wBvatms8',
    appId: '1:57141874608:web:84996caa438fb705be1075',
    messagingSenderId: '57141874608',
    projectId: 'gopeed-app',
    authDomain: 'gopeed-app.firebaseapp.com',
    storageBucket: 'gopeed-app.appspot.com',
    measurementId: 'G-E6W9RENP7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4TUgNPL-a9-SR_slysOeey4wVcWIVUQc',
    appId: '1:57141874608:android:80b8d079fd6383f0be1075',
    messagingSenderId: '57141874608',
    projectId: 'gopeed-app',
    storageBucket: 'gopeed-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPjOLF32G5bIb3uMaRnqI9bMdi7G_UpPg',
    appId: '1:57141874608:ios:e8de50977541b415be1075',
    messagingSenderId: '57141874608',
    projectId: 'gopeed-app',
    storageBucket: 'gopeed-app.appspot.com',
    iosBundleId: 'com.gopeed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPjOLF32G5bIb3uMaRnqI9bMdi7G_UpPg',
    appId: '1:57141874608:ios:e8de50977541b415be1075',
    messagingSenderId: '57141874608',
    projectId: 'gopeed-app',
    storageBucket: 'gopeed-app.appspot.com',
    iosBundleId: 'com.gopeed',
  );
}
